In [1]:
#Import dependencies
import pandas as pd

In [2]:
#Read csv
gdp_df = pd.read_csv('World_Bank_Files/Resources/etl_project_gdp.csv')

#grab the 4th row and set it to be the header
new_header = gdp_df.iloc[3]
gdp_df.columns = new_header

#remove first 4 rows from df
gdp_df = gdp_df.iloc[4:]

In [3]:
#drop extra columns
gdp_df = gdp_df.drop(columns=['Indicator Name', 'Indicator Code',1960.0,2020.0])
gdp_df = gdp_df.reset_index(drop = True)
gdp_df

3,Country Name,Country Code,1961.0,1962.0,1963.0,1964.0,1965.0,1966.0,1967.0,1968.0,...,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.685029,3.446055,-1.369863,4.198232,0.300000,5.700001,2.100000,1.999999,NaN,NaN
1,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.362441,0.426355,12.752287,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603
2,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.403933,3.471976,8.542188,4.954545,4.822628,0.943572,-2.580050,-0.147213,-2.003630,-0.624644
3,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.706892,2.545322,1.417526,1.001987,1.774487,2.218752,3.314805,3.802197,4.071301,2.240070
4,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.974958,-0.008070,-4.974444,-3.547597,2.504466,1.434140,3.709678,0.346072,1.588765,1.849238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.309907,4.375285,2.810262,3.439551,1.222168,4.095194,4.070950,4.225630,3.815620,4.171659
260,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.702307,-12.714823,2.392886,4.823415,-0.188591,-27.994439,-9.375060,-5.072010,0.752599,2.097414
261,South Africa,ZAF,3.844751,6.177883,7.373613,7.939782,6.122761,4.438308,7.196576,4.153445,...,3.039731,3.284168,2.213355,2.485200,1.846992,1.193733,0.399088,1.414513,0.787056,0.152583
262,Zambia,ZMB,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,1.248330,...,10.298223,5.564602,7.597593,5.057232,4.697992,2.920375,3.776679,3.504336,4.034378,1.441785
263,Zimbabwe,ZWE,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,1.970135,...,19.675323,14.193913,16.665429,1.989493,2.376929,1.779873,0.755869,4.704035,4.829674,-8.100000

In [4]:
gdp_df = gdp_df.rename(columns= {'Country Name':'Country Name',
 'Country Code':'Country Code',1961.0:'1961',1962.0:'1962', 1963.0:'1963', 1964.0:'1964', 1965.0:'1965',
 1966.0:'1966', 1967.0:'1967', 1968.0:'1968', 1969.0:'1969', 1970.0:'1970', 1971.0:'1971', 1972.0:'1972',
 1973.0:'1973', 1974.0:'1974', 1975.0:'1975', 1976.0:'1976', 1977.0:'1977', 1978.0:'1978', 1979.0:'1979',
 1980.0:'1980', 1981.0:'1981', 1982.0:'1982', 1983.0:'1983', 1984.0:'1984', 1985.0:'1985', 1986.0:'1986',
 1987.0:'1987', 1988.0:'1988', 1989.0:'1989', 1990.0:'1990', 1991.0:'1991', 1992.0:'1992', 1993.0:'1993',
 1994.0:'1994', 1995.0:'1995', 1996.0:'1996', 1997.0:'1997', 1998.0:'1998', 1999.0:'1999', 2000.0:'2000',
 2001.0:'2001', 2002.0:'2002', 2003.0:'2003', 2004.0:'2004', 2005.0:'2005', 2006.0:'2006', 2007.0:'2007',
 2008.0:'2008', 2009.0:'2009', 2010.0:'2010', 2011.0:'2011', 2012.0:'2012', 2013.0:'2013', 2014.0:'2014',
 2015.0:'2015', 2016.0:'2016', 2017.0:'2017', 2018.0:'2018', 2019.0:'2019'})

In [5]:
gdp_df.dtypes

3
Country Name     object
Country Code     object
1961            float64
1962            float64
1963            float64
                 ...
2015            float64
2016            float64
2017            float64
2018            float64
2019            float64
Length: 61, dtype: object

In [10]:
gdp_df.dtypes

3
Country Name    object
Country Code    object
1961            object
1962            object
1963            object
                 ...
2015            object
2016            object
2017            object
2018            object
2019            object
Length: 61, dtype: object

In [8]:
#read in regional metadata
regional_df = pd.read_csv('World_Bank_Files/Resources/etl_regional_metadata.csv')

In [9]:
#double check that the data types are the same for joining
regional_df.dtypes

Country Code    object
Region          object
IncomeGroup     object
SpecialNotes    object
TableName       object
dtype: object